### ISSUE TITLE
Installation Zip

### ISSUE THREAD

**Issue by adampax** [SeanChristopherConway/titanium-google-geofence#2]
Thanks for posting this module. Would it be possible to post the distribution zip file as well? Thanks

**Comment by SeanChristopherConway** [comment]
@adampax Yes I just pushed the distribution module, let me know how it goes. BTW-thanks for your mapbox module work :-)

**Comment by adampax** [comment]
Thanks a lot @SeanChristopherConway.  I'll get @raybelisle to buy you lunch!
